import { useState } from 'react';
import './WhitelistApplication.css';
import { submitRefundAddress } from '../../../supabase/refundService';

export default function WhitelistApplication() {
	const [formData, setFormData] = useState({
		xUsername: '',
		activityWallet: '',
		transactionHashes: '',
		compensationWallet: ''
	});
	const [submitted, setSubmitted] = useState(false);
	const [isSubmitting, setIsSubmitting] = useState(false);
	const [error, setError] = useState(null);
	const [showBook, setShowBook] = useState(false);

	const handleChange = (e) => {
		const { name, value } = e.target;
		setFormData(prev => ({ ...prev, [name]: value }));
	};

	const handleSubmit = async (e) => {
		e.preventDefault();
		if (!formData.xUsername || !formData.activityWallet || !formData.transactionHashes || !formData.compensationWallet) return;

		setIsSubmitting(true);
		setError(null);

		const result = await submitRefundAddress(formData);
		
		if (result.success) {
			setSubmitted(true);
		} else {
			setError('Failed to submit form. Please try again.');
		}
		
		setIsSubmitting(false);
	};

	return (
		<section className="wl-application-section" id="whitelist">
			{showBook && (
				<div className="ancient-book-overlay" onClick={() => setShowBook(false)}>
					<div className="ancient-book-modal" onClick={e => e.stopPropagation()}>
						<button className="book-close-btn" onClick={() => setShowBook(false)}>✕</button>
						<div className="book-content-inner">
							<h3 className="book-title">THE PATH FORWARD</h3>
							<p>This form is for everyone who was affected by the original Haunting Hoods launch.</p>
							<p>We want to clarify how we are proceeding.</p>
							<p>We will compensate the people who were affected by what happened.</p>
							<p>However, immediately using everything remaining to refund everyone would mean abandoning Haunting Hoods completely. We don't want to do that.</p>
							<p>We need time to rebuild the project and generate the revenue required to make the refunds possible.</p>

							<h4 className="book-subtitle">FOR NOW - THE RELAUNCH</h4>
							<p>Our current plan is to relaunch Haunting Hoods with 4444 NFTs.</p>
							<p>As the first part of the compensation process everyone who suffered a loss will receive a FREE MINT WHITELIST allocation for the relaunch.</p>
							<p>The number of free mints each wallet receives will depend on its historical impact, including the loss suffered and/or Hoods held.</p>
							<p>The greater the impact, the greater the free mint allocation.</p>
							<p>The eventual monetary compensation/refund will be handled after the relaunch using revenue generated by Haunting Hoods.</p>
							<p>We know this will take time, and we are not going to pretend otherwise.</p>
							<p>Our goal is to build the project, generate sustainable revenue through the mint, royalties and ecosystem and use those funds to make the affected users whole over time.</p>
							<p>All future project revenue and treasury activity will be transparent so you can see how the funds are being generated and used.</p>
							<p>We would rather take the time to rebuild Haunting Hoods properly and fulfill our commitment than immediately shut the project down and leave everyone with nothing.</p>

							<h4 className="book-subtitle">HISTORICAL ACTIVITY</h4>
							<p>The compensation review will be based on historical on-chain activity before the stop-trading announcement.</p>
							<p>If you continue buying or selling after the stop-trading announcement, those transactions will not be considered for the compensation calculation.</p>
							<p>We don't want anyone taking additional losses while we work on making this right.</p>
							<p>Please provide all relevant mint, buy and sell transaction hashes so we can accurately review your historical activity.</p>
							
							<p className="book-warning">⚠️ Please double-check your compensation address before submitting.</p>
							
							<p>We are taking the time to review everything properly so the allocation can be calculated as fairly and transparently as possible.</p>
							<p style={{ marginTop: '2rem', textAlign: 'center', color: '#ff4d4d', letterSpacing: '0.1em' }}>This is the first step toward making things right.</p>
						</div>
					</div>
				</div>
			)}
			<div className="wl-app-container seal-breaking-container">
				<div className="seal-breaking-eyebrow">THE PACT REMAINS</div>
				<h2 className="seal-breaking-title">RECLAIM YOUR TRIBUTE</h2>
				<p className="seal-breaking-subtitle loss-form-subtitle" style={{ maxWidth: '600px' }}>
					The Hoods do not forget their own. Your devotion shall not lead to ruin. Provide the sacred details below so we may accurately trace your path.
				</p>

				{!submitted ? (
					<form onSubmit={handleSubmit} className="whitelist-form loss-verification-form">
						<div className="form-group wl-address-input-group">
							<label className="wl-address-label">
								<strong>1. TRIBUTE IDENTITY</strong>
								<span>Your X/Twitter username</span>
							</label>
							<input
								type="text"
								name="xUsername"
								className="wl-address-input"
								placeholder="@username"
								value={formData.xUsername}
								onChange={handleChange}
								required
								disabled={isSubmitting}
								style={{ textAlign: 'left', marginTop: '0' }}
							/>
						</div>

						<div className="form-group wl-address-input-group">
							<label className="wl-address-label">
								<strong>2. THE SACRED WALLET</strong>
								<span>Wallet address used to mint/buy/sell Haunting Hoods</span>
							</label>
							<input
								type="text"
								name="activityWallet"
								className="wl-address-input"
								placeholder="0x..."
								value={formData.activityWallet}
								onChange={handleChange}
								required
								disabled={isSubmitting}
								style={{ textAlign: 'left', marginTop: '0' }}
							/>
						</div>

						<div className="form-group wl-address-input-group">
							<label className="wl-address-label">
								<strong>3. PROOFS OF DEVOTION</strong>
								<span>Please provide ALL relevant transaction hashes. This can include mint, buy, and sell transactions.</span>
								<span style={{ fontStyle: 'italic', color: '#ff4d4d', opacity: 0.8, marginTop: '0.5rem' }}>
									« You can submit multiple transaction hashes. Please enter one transaction hash per line. »
								</span>
							</label>
							<textarea
								name="transactionHashes"
								className="wl-address-input wl-textarea"
								placeholder="Transaction Hash 1:&#10;Transaction Hash 2:&#10;Transaction Hash 3:&#10;Transaction Hash 4:"
								value={formData.transactionHashes}
								onChange={handleChange}
								required
								disabled={isSubmitting}
								rows="5"
								style={{ textAlign: 'left', marginTop: '0', background: 'transparent' }}
							/>
						</div>

						<div className="form-group wl-address-input-group">
							<label className="wl-address-label">
								<strong>4. THE RECEPTACLE</strong>
								<span>Wallet address where you want your relaunch compensation/rewards sent</span>
							</label>
							<input
								type="text"
								name="compensationWallet"
								className="wl-address-input"
								placeholder="0x..."
								value={formData.compensationWallet}
								onChange={handleChange}
								required
								disabled={isSubmitting}
								style={{ textAlign: 'left', marginTop: '0' }}
							/>
							<p className="form-warning" style={{ fontSize: '0.75rem', marginTop: '0.8rem', letterSpacing: '0.05em' }}>⚠️ PLEASE DOUBLE-CHECK THIS ADDRESS BEFORE SUBMITTING.</p>
						</div>

						{error && <p className="form-error-message">{error}</p>}
						
						<div style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
							<button type="submit" className="wl-submit-btn mint-btn" disabled={isSubmitting} style={{ flex: 1 }}>
								{isSubmitting ? 'SUMMONING...' : 'RECLAIM TRIBUTE'}
							</button>
							<button type="button" className="wl-submit-btn read-btn" onClick={() => setShowBook(true)} style={{ flex: 1, background: 'transparent', border: '1px solid #ff4d4d', color: '#ff4d4d' }}>
								PLEASE READ
							</button>
						</div>
					</form>
				) : (
					<div className="wl-success-message" style={{ marginTop: '2rem' }}>
						<h3 style={{ color: '#ff4d4d', letterSpacing: '0.1em' }}>TRIBUTE RECEIVED</h3>
						<p style={{ color: '#888', fontSize: '0.9rem' }}>Your devotion is recognized. We will review your path and honor your loyalty.</p>
					</div>
				)}
			</div>

			<div className="wl-app-container seal-breaking-container pvp-teaser-container" style={{ textAlign: 'center', maxWidth: '800px' }}>
				<div className="seal-breaking-eyebrow">THE HUNT EVOLVES</div>
				<h2 className="seal-breaking-title">BLOOD IN THE ARENA</h2>
				<p className="seal-breaking-subtitle loss-form-subtitle" style={{ maxWidth: '600px', margin: '0 auto 2rem' }}>
					Your tribute is just the beginning. Sharpen your blades and prepare your Hoods. 
					The gates to the Player vs Player Arena will soon open... and only the ruthless will survive.
					<span style={{ display: 'block', color: '#ff4d4d', marginTop: '1.2rem', letterSpacing: '0.1em', fontWeight: 600 }}>
						EMERGE VICTORIOUS. MOVE AHEAD IN RECKONING.
					</span>
				</p>
				<div className="pvp-video-wrapper">
					<video 
						src="/videos/pvp-teaser.mp4" 
						autoPlay 
						loop 
						muted 
						playsInline 
						className="pvp-teaser-video"
					></video>
					<div className="video-glow-overlay"></div>
				</div>
			</div>
		</section>
	);
}
